// Generated by gencpp from file monitoring_package/poseRequest.msg
// DO NOT EDIT!


#ifndef MONITORING_PACKAGE_MESSAGE_POSEREQUEST_H
#define MONITORING_PACKAGE_MESSAGE_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monitoring_package
{
template <class ContainerAllocator>
struct poseRequest_
{
  typedef poseRequest_<ContainerAllocator> Type;

  poseRequest_()
    {
    }
  poseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::monitoring_package::poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monitoring_package::poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct poseRequest_

typedef ::monitoring_package::poseRequest_<std::allocator<void> > poseRequest;

typedef boost::shared_ptr< ::monitoring_package::poseRequest > poseRequestPtr;
typedef boost::shared_ptr< ::monitoring_package::poseRequest const> poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monitoring_package::poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monitoring_package::poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace monitoring_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monitoring_package::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::monitoring_package::poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::monitoring_package::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monitoring_package/poseRequest";
  }

  static const char* value(const ::monitoring_package::poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monitoring_package::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::monitoring_package::poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monitoring_package::poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monitoring_package::poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::monitoring_package::poseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MONITORING_PACKAGE_MESSAGE_POSEREQUEST_H
