// Generated by gencpp from file monitoring_package/poseResponse.msg
// DO NOT EDIT!


#ifndef MONITORING_PACKAGE_MESSAGE_POSERESPONSE_H
#define MONITORING_PACKAGE_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monitoring_package
{
template <class ContainerAllocator>
struct poseResponse_
{
  typedef poseResponse_<ContainerAllocator> Type;

  poseResponse_()
    : x(0.0)
    , y(0.0)  {
    }
  poseResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::monitoring_package::poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monitoring_package::poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct poseResponse_

typedef ::monitoring_package::poseResponse_<std::allocator<void> > poseResponse;

typedef boost::shared_ptr< ::monitoring_package::poseResponse > poseResponsePtr;
typedef boost::shared_ptr< ::monitoring_package::poseResponse const> poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monitoring_package::poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monitoring_package::poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::monitoring_package::poseResponse_<ContainerAllocator1> & lhs, const ::monitoring_package::poseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::monitoring_package::poseResponse_<ContainerAllocator1> & lhs, const ::monitoring_package::poseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace monitoring_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monitoring_package::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::monitoring_package::poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::monitoring_package::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monitoring_package/poseResponse";
  }

  static const char* value(const ::monitoring_package::poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monitoring_package::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::monitoring_package::poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monitoring_package::poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monitoring_package::poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monitoring_package::poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONITORING_PACKAGE_MESSAGE_POSERESPONSE_H
