// Generated by gencpp from file monitoring_package/pose.msg
// DO NOT EDIT!


#ifndef MONITORING_PACKAGE_MESSAGE_POSE_H
#define MONITORING_PACKAGE_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <monitoring_package/poseRequest.h>
#include <monitoring_package/poseResponse.h>


namespace monitoring_package
{

struct pose
{

typedef poseRequest Request;
typedef poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose
} // namespace monitoring_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::monitoring_package::pose > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::monitoring_package::pose&) { return value(); }
};

template<>
struct DataType< ::monitoring_package::pose > {
  static const char* value()
  {
    return "monitoring_package/pose";
  }

  static const char* value(const ::monitoring_package::pose&) { return value(); }
};


// service_traits::MD5Sum< ::monitoring_package::poseRequest> should match
// service_traits::MD5Sum< ::monitoring_package::pose >
template<>
struct MD5Sum< ::monitoring_package::poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::monitoring_package::pose >::value();
  }
  static const char* value(const ::monitoring_package::poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::monitoring_package::poseRequest> should match
// service_traits::DataType< ::monitoring_package::pose >
template<>
struct DataType< ::monitoring_package::poseRequest>
{
  static const char* value()
  {
    return DataType< ::monitoring_package::pose >::value();
  }
  static const char* value(const ::monitoring_package::poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::monitoring_package::poseResponse> should match
// service_traits::MD5Sum< ::monitoring_package::pose >
template<>
struct MD5Sum< ::monitoring_package::poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::monitoring_package::pose >::value();
  }
  static const char* value(const ::monitoring_package::poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::monitoring_package::poseResponse> should match
// service_traits::DataType< ::monitoring_package::pose >
template<>
struct DataType< ::monitoring_package::poseResponse>
{
  static const char* value()
  {
    return DataType< ::monitoring_package::pose >::value();
  }
  static const char* value(const ::monitoring_package::poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MONITORING_PACKAGE_MESSAGE_POSE_H
