// Generated by gencpp from file monitoring_package/poseVelocity.msg
// DO NOT EDIT!


#ifndef MONITORING_PACKAGE_MESSAGE_POSEVELOCITY_H
#define MONITORING_PACKAGE_MESSAGE_POSEVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monitoring_package
{
template <class ContainerAllocator>
struct poseVelocity_
{
  typedef poseVelocity_<ContainerAllocator> Type;

  poseVelocity_()
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_y(0.0)  {
    }
  poseVelocity_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vel_x_type;
  _vel_x_type vel_x;

   typedef float _vel_y_type;
  _vel_y_type vel_y;





  typedef boost::shared_ptr< ::monitoring_package::poseVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monitoring_package::poseVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct poseVelocity_

typedef ::monitoring_package::poseVelocity_<std::allocator<void> > poseVelocity;

typedef boost::shared_ptr< ::monitoring_package::poseVelocity > poseVelocityPtr;
typedef boost::shared_ptr< ::monitoring_package::poseVelocity const> poseVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monitoring_package::poseVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monitoring_package::poseVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::monitoring_package::poseVelocity_<ContainerAllocator1> & lhs, const ::monitoring_package::poseVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vel_x == rhs.vel_x &&
    lhs.vel_y == rhs.vel_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::monitoring_package::poseVelocity_<ContainerAllocator1> & lhs, const ::monitoring_package::poseVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace monitoring_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monitoring_package::poseVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitoring_package::poseVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitoring_package::poseVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monitoring_package::poseVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d133e2df0fdd42b7663a488cd2710f";
  }

  static const char* value(const ::monitoring_package::poseVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d133e2df0fdd42ULL;
  static const uint64_t static_value2 = 0xb7663a488cd2710fULL;
};

template<class ContainerAllocator>
struct DataType< ::monitoring_package::poseVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monitoring_package/poseVelocity";
  }

  static const char* value(const ::monitoring_package::poseVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monitoring_package::poseVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 vel_x\n"
"float32 vel_y\n"
"\n"
;
  }

  static const char* value(const ::monitoring_package::poseVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monitoring_package::poseVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vel_x);
      stream.next(m.vel_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monitoring_package::poseVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monitoring_package::poseVelocity_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.vel_x);
    s << indent << "vel_y: ";
    Printer<float>::stream(s, indent + "  ", v.vel_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONITORING_PACKAGE_MESSAGE_POSEVELOCITY_H
