(cl:defpackage monitoring_package-srv
  (:use )
  (:export
   "DISTANCEANDAVERAGEVELOCITY"
   "<DISTANCEANDAVERAGEVELOCITY-REQUEST>"
   "DISTANCEANDAVERAGEVELOCITY-REQUEST"
   "<DISTANCEANDAVERAGEVELOCITY-RESPONSE>"
   "DISTANCEANDAVERAGEVELOCITY-RESPONSE"
   "POSE"
   "<POSE-REQUEST>"
   "POSE-REQUEST"
   "<POSE-RESPONSE>"
   "POSE-RESPONSE"
  ))

